region: ap-northeast-1
cluster: sample-alb-backend
service: sample-alb-backend
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      path: ../terraform.tfstate
appspec: null
